format = """
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$nodejs\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character
"""

[fill]
symbol = ' '

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '../'
truncate_to_repo = false

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
disabled = true

[nodejs]
detect_files = ["package.json", ".node-version"]
detect_extensions = ["js", "ts"]
style = 'yellow'
symbol = ' '
format = "[$symbol($version )]($style)"

[python]
disabled = true
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "requirements.txt", ".python-version"]
format = "[🐍 $version ](fg:blue)"

[lua]
detect_extensions = ["lua"]
format = "[🌙 $version ](fg:blue)"

[jobs]
disabled = true

[cmd_duration]
disabled = true
